packages:
  - 'apps/*'
  - 'packages/*'
  - 'backend'
allowBuilds:
  '@nestjs/core': false
  '@parcel/watcher': true
  unrs-resolver: false
  onnxruntime-node: true
  esbuild: true
  protobufjs: true
  sharp: true
