ALTER TABLE mentor
  ADD COLUMN IF NOT EXISTS usuario_id UUID UNIQUE REFERENCES usuario(usuario_id),
  ADD COLUMN IF NOT EXISTS esta_verificado BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS esta_aprobado BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS tiene_restriccion BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS perfil JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS configuracion JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS motivo_desactivacion TEXT;